### ISSUE TITLE
代码段下端总是有滚动条

### ISSUE THREAD

**Issue by Stevens1995** [0x2E/Material-T#38]
![image](https://user-images.githubusercontent.com/19243114/58409600-ff6e8080-80a2-11e9-93f1-1b7874bd8aaa.png)

**Comment by 0x2E** [comment]
根目录的 _config.yml 中按下面这样的配置来关掉 Hexo 默认代码高亮：
```yml
// 弃用 Hexo 默认代码高亮
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:
```

然后 `hexo clean`，`hexo g`
