### ISSUE TITLE
重做归档页导致升级后可能出现的问题

### ISSUE THREAD

**Issue by 0x2E** [0x2E/Material-T#54]
# 概述

PR #53 对主题的归档模式做出大量调整：
1. 重做归档页（Archive Page）
2. 新增标签归档页（Tags Page）和分类归档页（Categories Page）

所以升级之后可能会遇到如下问题

# Archive 页为空

新版本不再需要此前安装时所要求的『关闭归档页的默认分页』操作，请在 Hexo 配置文件中将如下的 `per_page` 属性设置正常值
<s>
```yml
// 关闭归档页的默认分页：
archive_generator:
  per_page: 0  
  yearly: true
  monthly: true
  daily: false
  order_by: -date
```
</s>

# 如何使用 Tag 和 Category

请参照 [Hexo 官方文档](https://hexo.io/zh-cn/docs/front-matter#%E5%88%86%E7%B1%BB%E5%92%8C%E6%A0%87%E7%AD%BE)

# 如何创建 Tags Page 和  Categories Page

都是自动生成的。

# 其他

若出现其他问题请在下方贴出~
