### ISSUE TITLE
gitalk 留言无效问题

### ISSUE THREAD

**Issue by scramblecode** [0x2E/Material-T#72]
![image](https://user-images.githubusercontent.com/54971536/64420250-69022000-d0d1-11e9-905b-1ad9c83e1142.png)
按照配置配置完之后界面并没有什么变化

**Comment by 0x2E** [comment]
```yml
post:
  comments: 
    enable: true
    type: gitalk 
```
这个配置了吗
